apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend  # Upewnij się, że etykieta w Deployment backend jest zgodna
  ports:
    - protocol: TCP
      port: 3000        # Port, na którym usługa będzie dostępna
      targetPort: 3000  # Port kontenera, na którym działa aplikacja backend
  type: ClusterIP      # Użyj ClusterIP, aby usługa była dostępna tylko wewnątrz klastra
